services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_crud
      - MYSQL_USER=user_crud
      - MYSQL_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-networks


  backend-nestjs:
    build: ./backend-nesjs 
    container_name: nestjs_backend
    restart: always
    depends_on:
      - mysql
    ports: 
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user_crud
      - DB_PASSWORD=root
      - DB_NAME=db_crud
    networks:
      - app-networks

  frontend-react:
    build: ./frontend-react
    container_name: react_frontend
    restart: always
    depends_on:
      - backend-nestjs
    ports:
      - "5173:5173"
    networks:
      - app-networks
  


networks:
  app-networks:
    driver: bridge
  
volumes:
  mysql: